spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsr?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 525757
    driver-class-name:  com.mysql.jdbc.Driver

  security:
    user:
      name: hh
      password:  525757
      roles: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
